### ISSUE TITLE
Annotate submissions with comments

### ISSUE THREAD

**Issue by e0d** [openedx/edx-ora2#1944]
Annotation on work(google docs commenting style)- Highlight a line and give comments about speciﬁc not just on the whole work- threading of comments

**Comment by Colin-Fredericks** [comment]
Probably difficult to implement, but potentially very useful in writing-type courses. You might be able to co-opt some of our Annotation tool back-end for this.

**Comment by e0d** [comment]
Closing in favor of https://github.com/openedx/edx-ora2/issues/1945
