### ISSUE TITLE
Allow individual learner extension for ORA responses

### ISSUE THREAD

**Issue by e0d** [openedx/edx-ora2#1959]
Allow individual learner extension for ORA responses.  Instructors will be able to offer extensions on ORA assignments as they had for other types of assignements.

**Comment by Ian2012** [comment]
I just wanted to let you know that I'm planning on taking this issue.

- Is there a plan for it?
- Documentation from where to start?
- Any links or discussions?
- Any scenarios that this extension shouldn't cover?

**Comment by e0d** [comment]
@colin-fredericks @Daniel-hershel I wanted to call your attention to this PR which implements this feature #2026

**Comment by mariajgrimaldi** [comment]
Hi there! 

We've encountered this ORA improvement as part of the on-campus learning experience effort (Project with the Spanish Consortium). Specifically, we were requested to:

> Integrate the ORA module into the individual deadline extensions module of the LMS instructor dashboard

[Here's](https://github.com/openedx/edx-ora2/pull/2026) our first implementation approach for the improvement! Please, let us know what's the next step for this to land :)

**Comment by Colin-Fredericks** [comment]
@e0d Thanks Ed! We very much appreciate it - we've gotten more requests for ORA extensions in the past few months than we did in the previous few years.

**Comment by e0d** [comment]
@Daniel-hershel given that this will be handled by your current work around ORA dates, should I change the team to 2U and link this to your other ticket?

**Comment by e0d** [comment]
Is this work bundled with the UX improvements epic #2003

**Comment by e0d** [comment]
@Ian2012 given that this will be handled elsewhere, I think we should close.  Let me know if you disagree.

**Comment by e0d** [comment]
@Ian2012 checking back, should this be closed?

**Comment by Ian2012** [comment]
@e0d Yes, this should be closed
